[package]
name = "zeebe-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
zeebe-client = { path = "../client" }
clap = { version = "3.2", features = ["derive", "env"] }
color-eyre = "0.6"
tonic = "0.7"
tokio = { version = "1", features=["full"] }