name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Cache
        uses: Swatinem/rust-cache@v2.7.5

      - name: Build
        run: cargo build
